# 默认配置

# 系统基本配置
basic:
  name: forest
  # 系统并发限制，如果调整此限制，需要确认tracer中的大小也需要调整
  requestLimit: 100
  listen: :7001
  timeout: 30s

# redis 配置
redis:
  # 可以配置为下面的形式，则从env中获取REDIS_URI对应的字符串来当redis连接串
  # uri: REDIS_URI
  # uri: redis://:pass@127.0.0.1:6379/?slow=200ms&maxProcessing=1000
  uri: redis://127.0.0.1:6379/?slow=200ms&maxProcessing=1000

# postgres postgres配置
postgres:
  # 可以配置为下面的形式，则从env中获取POSTGRES_URI对应的字符串来当postgres连接串
  # uri: POSTGRES_URI
  uri: postgresql://vicanso:A123456@127.0.0.1:5432/beginner?maxIdleConns=5&maxIdleTime=30m&maxOpenConns=100
